# service
# kubectl create service clusterip es-kibane -n kube-system --clusterip=None --tcp=9200:9200 --tcp=9300:9300 --dry-run -o yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: es9200
    port: 9200
    protocol: TCP
    targetPort: 9200
  clusterIP: None
  selector:
    app: elasticsearch
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
  type: NodePort
  selector:
    app: kibana




---
# configMap

apiVersion: v1
kind: ConfigMap
metadata:
  name: es-conf
data:
  elasticsearch.yml: |
    node.name: elasticsearch
    cluster.name: k8s-elk
    cluster.initial_master_nodes: elasticsearch
    #discovery.zen.minimum_master_nodes: 1
    node.master: true
    node.data: true
    discovery.type: single-node
    network.host: 0.0.0.0
  kibana.yml: |
    server:
      name: kibana
      host: '0'
    elasticsearch:
      hosts: [http://elasticsearch:9200]
    xpack.monitoring.ui.container.elasticsearch.enabled: false

---
# StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
        ports:
          - name: esport
            containerPort: 9200
        env:
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"

        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: es-data
          - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
            name: elasticsearch-yml

      volumes:
        - name: es-data
          hostPath:
            path: /np/elk/elasticsearch/data
        - name: elasticsearch-yml
          configMap:
            name: es-conf
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  serviceName: kibana
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.4.1
        ports:
         - name: kibana-port
           containerPort: 5601
        # env:
        #   - name: ELASTICSEARCH_URL
        #     value: http://es-kibana-0.es-kibana.default:9200
        volumeMounts:
          - mountPath: /usr/share/kibana/config/kibana.yml
            subPath: kibana.yml
            name: kibana-yml

      volumes:
        - name: kibana-yml
          configMap:
            name: es-conf
            items:
              - key: kibana.yml
                path: kibana.yml

---
# nodeport service

apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-kibana
  name: es-nodeport-svc
spec:
  ports:
  - name: 9200-9200
    port: 9200
    protocol: TCP
    targetPort: 9200
    nodePort: 30920
  - name: 5601-5601
    port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 30560
  selector:
    app: es-kibana
  type: NodePort
